/**
 * Minimal markdown → styled HTML template for cloud-fallback emails.
 *
 * Ported from Mac's lib/calendar/briefing-html.ts with identical styling
 * (Midnight Portfolio theme — dark navy/black + gold accent) so recipients
 * can't easily tell a fallback email apart by eye. The italic footer note
 * slot is the only visible difference when populated.
 */

const COLORS = {
  bg: "#080B12",
  panel: "#0F1219",
  border: "#1E2534",
  text: "#E2E6F0",
  dimText: "#8B95A8",
  gold: "#C9A44E",
  heading: "#F0F2F7",
};

// Tables use a light palette regardless of the surrounding dark email so they
// print cleanly to paper and remain handwriting-friendly. Mirrors Mac-side
// lib/calendar/briefing-html.ts (locked 2026-04-28). Empty / em-dash cells
// get extra vertical padding so they're tall enough to write a value in pen.
const TABLE_COLORS = {
  headerBg: "#F4EFE0",
  headerText: "#3A2E0F",
  bodyBg: "#FFFFFF",
  bodyText: "#1A1A1A",
  border: "#777777",
  labelText: "#1A1A1A",
};

export function briefingToHtml(
  markdown: string,
  title: string,
  footerNote?: string
): string {
  const bodyHtml = convertMarkdown(markdown);
  const footerNoteHtml = footerNote
    ? `<p style="margin:6px 0 0; font-size:11px; color:${COLORS.dimText}; font-style:italic;">${escapeHtml(footerNote)}</p>`
    : "";

  return `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body style="margin:0; padding:0; background-color:${COLORS.bg}; font-family:system-ui,-apple-system,sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background-color:${COLORS.bg};">
    <tr><td align="center" style="padding:24px 16px;">
      <table width="600" cellpadding="0" cellspacing="0" style="max-width:600px; width:100%;">
        <tr><td style="padding:20px 24px; background-color:${COLORS.panel}; border:1px solid ${COLORS.border}; border-radius:12px 12px 0 0;">
          <h1 style="margin:0; font-size:20px; color:${COLORS.gold}; font-weight:600;">Vanguard Dashboard</h1>
          <p style="margin:6px 0 0; font-size:13px; color:${COLORS.dimText};">${escapeHtml(title)}</p>
        </td></tr>
        <tr><td style="padding:24px; background-color:${COLORS.panel}; border-left:1px solid ${COLORS.border}; border-right:1px solid ${COLORS.border}; border-bottom:1px solid ${COLORS.border}; border-radius:0 0 12px 12px; color:${COLORS.text}; font-size:14px; line-height:1.65;">
          ${bodyHtml}
        </td></tr>
        <tr><td style="padding:16px 24px; text-align:center;">
          <p style="margin:0; font-size:11px; color:${COLORS.dimText};">Generated by Vanguard Dashboard</p>
          ${footerNoteHtml}
        </td></tr>
      </table>
    </td></tr>
  </table>
</body>
</html>`;
}

const tableRowRe = /^\|(.+)\|\s*$/;
const tableSeparatorRe = /^\|(\s*:?-+:?\s*\|)+\s*$/;

function parseTableRow(line: string): string[] {
  return line.trim().slice(1, -1).split("|").map((s) => s.trim());
}

function isFillableCell(text: string): boolean {
  const t = text.trim();
  return t === "" || t === "—" || t === "-" || t === "–";
}

function renderTable(headers: string[], rows: string[][]): string {
  const headerCells = headers
    .map(
      (h) =>
        `<th style="border:1px solid ${TABLE_COLORS.border}; padding:8px 10px; background-color:${TABLE_COLORS.headerBg}; color:${TABLE_COLORS.headerText}; font-size:11px; font-weight:600; text-align:left; text-transform:uppercase; letter-spacing:0.06em; white-space:nowrap;">${inlineFormat(h)}</th>`,
    )
    .join("");
  const bodyRows = rows
    .map((row) => {
      const cells = row
        .map((c, idx) => {
          const fillable = isFillableCell(c);
          const isLabel = idx === 0;
          const content = fillable && !isLabel ? "&nbsp;" : inlineFormat(c) || "&nbsp;";
          const padding = !isLabel && fillable ? "14px 10px" : "8px 10px";
          const align = !isLabel ? "text-align:right;" : "";
          const numAlign = !isLabel ? "font-variant-numeric:tabular-nums;" : "";
          const cellColor = isLabel ? TABLE_COLORS.labelText : TABLE_COLORS.bodyText;
          const fontWeight = isLabel ? "font-weight:500;" : "";
          return `<td style="border:1px solid ${TABLE_COLORS.border}; padding:${padding}; background-color:${TABLE_COLORS.bodyBg}; color:${cellColor}; font-size:13px; ${fontWeight} ${align} ${numAlign}">${content}</td>`;
        })
        .join("");
      return `<tr>${cells}</tr>`;
    })
    .join("");
  return `<table cellpadding="0" cellspacing="0" style="border-collapse:collapse; margin:14px 0; width:100%; border:1px solid ${TABLE_COLORS.border}; background-color:${TABLE_COLORS.bodyBg};">
<thead><tr>${headerCells}</tr></thead>
<tbody>${bodyRows}</tbody>
</table>`;
}

function convertMarkdown(md: string): string {
  const lines = md.split("\n");
  const out: string[] = [];
  let inList = false;
  const closeList = () => {
    if (inList) {
      out.push("</ul>");
      inList = false;
    }
  };

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];

    // Markdown table block — mirror Mac-side lookahead detection.
    if (
      tableRowRe.test(line.trim()) &&
      i + 1 < lines.length &&
      tableSeparatorRe.test(lines[i + 1].trim())
    ) {
      closeList();
      const headerCells = parseTableRow(line);
      let j = i + 2;
      const dataRows: string[][] = [];
      while (j < lines.length && tableRowRe.test(lines[j].trim())) {
        const cells = parseTableRow(lines[j]);
        if (!tableSeparatorRe.test(lines[j].trim())) dataRows.push(cells);
        j++;
      }
      out.push(renderTable(headerCells, dataRows));
      i = j - 1;
      continue;
    }

    if (/^---+$/.test(line.trim())) {
      closeList();
      out.push(`<hr style="border:none; border-top:1px solid ${COLORS.border}; margin:16px 0;">`);
      continue;
    }

    if (line.startsWith("### ")) {
      closeList();
      out.push(`<h3 style="margin:20px 0 8px; font-size:15px; color:${COLORS.heading}; font-weight:600;">${inlineFormat(line.slice(4))}</h3>`);
      continue;
    }
    if (line.startsWith("## ")) {
      closeList();
      out.push(`<h2 style="margin:24px 0 10px; font-size:17px; color:${COLORS.gold}; font-weight:600; border-bottom:1px solid ${COLORS.border}; padding-bottom:6px;">${inlineFormat(line.slice(3))}</h2>`);
      continue;
    }
    if (line.startsWith("# ")) {
      closeList();
      out.push(`<h1 style="margin:0 0 16px; font-size:20px; color:${COLORS.heading}; font-weight:700;">${inlineFormat(line.slice(2))}</h1>`);
      continue;
    }

    if (line.startsWith("> ")) {
      closeList();
      out.push(`<p style="margin:8px 0; padding:8px 12px; border-left:3px solid ${COLORS.gold}; color:${COLORS.dimText}; font-size:13px;">${inlineFormat(line.slice(2))}</p>`);
      continue;
    }

    const bulletMatch = line.match(/^(\s*)[-*]\s+(.+)/);
    const numberedMatch = line.match(/^(\s*)\d+\.\s+(.+)/);
    if (bulletMatch || numberedMatch) {
      const m = bulletMatch ?? numberedMatch!;
      if (!inList) {
        out.push(`<ul style="margin:8px 0; padding-left:20px;">`);
        inList = true;
      }
      out.push(`<li style="margin:4px 0; color:${COLORS.text};">${inlineFormat(m[2])}</li>`);
      continue;
    }

    if (line.trim() === "") {
      closeList();
      continue;
    }

    closeList();
    out.push(`<p style="margin:8px 0; color:${COLORS.text};">${inlineFormat(line)}</p>`);
  }

  closeList();
  return out.join("\n");
}

function inlineFormat(text: string): string {
  let t = text;
  t = t.replace(/\[([^\]]+)\]\(([^)]+)\)/g, `<a href="$2" style="color:${COLORS.gold}; text-decoration:underline;">$1</a>`);
  // Bold inherits parent color so light-bg table cells render dark-on-light
  // (white-on-white bug if pinned to heading color). Same fix as Mac side.
  t = t.replace(/\*\*(.+?)\*\*/g, `<strong>$1</strong>`);
  t = t.replace(/__(.+?)__/g, `<strong>$1</strong>`);
  t = t.replace(/\*(.+?)\*/g, "<em>$1</em>");
  t = t.replace(/_(.+?)_/g, "<em>$1</em>");
  t = t.replace(/`(.+?)`/g, `<code style="background:rgba(127,127,127,0.18); padding:1px 5px; border-radius:3px; font-family:ui-monospace,Menlo,Consolas,monospace;">$1</code>`);
  return t;
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}
