/**
 * Minimal markdown → styled HTML template for cloud-fallback emails.
 *
 * Ported from Mac's lib/calendar/briefing-html.ts with identical styling
 * (Midnight Portfolio theme — dark navy/black + gold accent) so recipients
 * can't easily tell a fallback email apart by eye. The italic footer note
 * slot is the only visible difference when populated.
 */

const COLORS = {
  bg: "#080B12",
  panel: "#0F1219",
  border: "#1E2534",
  text: "#E2E6F0",
  dimText: "#8B95A8",
  gold: "#C9A44E",
  heading: "#F0F2F7",
};

export function briefingToHtml(
  markdown: string,
  title: string,
  footerNote?: string
): string {
  const bodyHtml = convertMarkdown(markdown);
  const footerNoteHtml = footerNote
    ? `<p style="margin:6px 0 0; font-size:11px; color:${COLORS.dimText}; font-style:italic;">${escapeHtml(footerNote)}</p>`
    : "";

  return `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body style="margin:0; padding:0; background-color:${COLORS.bg}; font-family:system-ui,-apple-system,sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background-color:${COLORS.bg};">
    <tr><td align="center" style="padding:24px 16px;">
      <table width="600" cellpadding="0" cellspacing="0" style="max-width:600px; width:100%;">
        <tr><td style="padding:20px 24px; background-color:${COLORS.panel}; border:1px solid ${COLORS.border}; border-radius:12px 12px 0 0;">
          <h1 style="margin:0; font-size:20px; color:${COLORS.gold}; font-weight:600;">Vanguard Dashboard</h1>
          <p style="margin:6px 0 0; font-size:13px; color:${COLORS.dimText};">${escapeHtml(title)}</p>
        </td></tr>
        <tr><td style="padding:24px; background-color:${COLORS.panel}; border-left:1px solid ${COLORS.border}; border-right:1px solid ${COLORS.border}; border-bottom:1px solid ${COLORS.border}; border-radius:0 0 12px 12px; color:${COLORS.text}; font-size:14px; line-height:1.65;">
          ${bodyHtml}
        </td></tr>
        <tr><td style="padding:16px 24px; text-align:center;">
          <p style="margin:0; font-size:11px; color:${COLORS.dimText};">Generated by Vanguard Dashboard</p>
          ${footerNoteHtml}
        </td></tr>
      </table>
    </td></tr>
  </table>
</body>
</html>`;
}

function convertMarkdown(md: string): string {
  const lines = md.split("\n");
  const out: string[] = [];
  let inList = false;
  const closeList = () => {
    if (inList) {
      out.push("</ul>");
      inList = false;
    }
  };

  for (const rawLine of lines) {
    const line = rawLine;

    if (/^---+$/.test(line.trim())) {
      closeList();
      out.push(`<hr style="border:none; border-top:1px solid ${COLORS.border}; margin:16px 0;">`);
      continue;
    }

    if (line.startsWith("### ")) {
      closeList();
      out.push(`<h3 style="margin:20px 0 8px; font-size:15px; color:${COLORS.heading}; font-weight:600;">${inlineFormat(line.slice(4))}</h3>`);
      continue;
    }
    if (line.startsWith("## ")) {
      closeList();
      out.push(`<h2 style="margin:24px 0 10px; font-size:17px; color:${COLORS.gold}; font-weight:600; border-bottom:1px solid ${COLORS.border}; padding-bottom:6px;">${inlineFormat(line.slice(3))}</h2>`);
      continue;
    }
    if (line.startsWith("# ")) {
      closeList();
      out.push(`<h1 style="margin:0 0 16px; font-size:20px; color:${COLORS.heading}; font-weight:700;">${inlineFormat(line.slice(2))}</h1>`);
      continue;
    }

    if (line.startsWith("> ")) {
      closeList();
      out.push(`<p style="margin:8px 0; padding:8px 12px; border-left:3px solid ${COLORS.gold}; color:${COLORS.dimText}; font-size:13px;">${inlineFormat(line.slice(2))}</p>`);
      continue;
    }

    const bulletMatch = line.match(/^(\s*)[-*]\s+(.+)/);
    const numberedMatch = line.match(/^(\s*)\d+\.\s+(.+)/);
    if (bulletMatch || numberedMatch) {
      const m = bulletMatch ?? numberedMatch!;
      if (!inList) {
        out.push(`<ul style="margin:8px 0; padding-left:20px;">`);
        inList = true;
      }
      out.push(`<li style="margin:4px 0; color:${COLORS.text};">${inlineFormat(m[2])}</li>`);
      continue;
    }

    if (line.trim() === "") {
      closeList();
      continue;
    }

    closeList();
    out.push(`<p style="margin:8px 0; color:${COLORS.text};">${inlineFormat(line)}</p>`);
  }

  closeList();
  return out.join("\n");
}

function inlineFormat(text: string): string {
  let t = text;
  t = t.replace(/\[([^\]]+)\]\(([^)]+)\)/g, `<a href="$2" style="color:${COLORS.gold}; text-decoration:underline;">$1</a>`);
  t = t.replace(/\*\*(.+?)\*\*/g, `<strong style="color:${COLORS.heading};">$1</strong>`);
  t = t.replace(/__(.+?)__/g, `<strong style="color:${COLORS.heading};">$1</strong>`);
  t = t.replace(/\*(.+?)\*/g, "<em>$1</em>");
  t = t.replace(/_(.+?)_/g, "<em>$1</em>");
  t = t.replace(/`(.+?)`/g, `<code style="background:${COLORS.bg}; padding:1px 4px; border-radius:3px;">$1</code>`);
  return t;
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}
