-- Calendar events from WSH (company-specific) and Claude (macro).
-- WSH provides earnings dates, analyst meetings, and major events for portfolio holdings.
-- Claude researches macro events (FOMC, CPI, jobs reports, etc.) not available via TWS API.
-- Both sources unified in one table, differentiated by `source` column.

CREATE TABLE calendar_events (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  source TEXT NOT NULL,                -- 'wsh' | 'claude_macro' | 'manual'
  event_type TEXT NOT NULL,            -- 'earnings' | 'analyst_meeting' | 'conference'
                                       -- | 'split' | 'fomc' | 'cpi' | 'jobs'
                                       -- | 'gdp' | 'pmi' | 'retail_sales' | 'housing'
                                       -- | 'other_macro' | 'other'
  event_date TEXT NOT NULL,            -- YYYY-MM-DD
  event_time TEXT,                     -- HH:MM or 'BMO'/'AMC'/'TAS' for earnings timing
  title TEXT NOT NULL,
  description TEXT,

  -- Company-specific (WSH events)
  security_id INTEGER REFERENCES securities(id),
  symbol TEXT,                         -- Denormalized for display convenience
  ib_con_id INTEGER,

  -- Macro-specific (Claude events)
  expected_impact TEXT,                -- 'high' | 'medium' | 'low'
  consensus_estimate TEXT,             -- e.g., "3.2%" or "250K"
  previous_value TEXT,                 -- Previous reading for comparison

  -- WSH raw data (undocumented format — store for debugging/iteration)
  raw_json TEXT,

  -- Dedup + metadata
  source_key TEXT UNIQUE NOT NULL,     -- e.g., 'wsh:8314:earnings:2026-04-15' or 'claude_macro:fomc:2026-04-01'
  week_of TEXT,                        -- YYYY-MM-DD (Monday of the week this was fetched for)
  fetched_at TEXT NOT NULL DEFAULT (datetime('now')),
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX idx_calendar_events_date ON calendar_events(event_date);
CREATE INDEX idx_calendar_events_security ON calendar_events(security_id);
CREATE INDEX idx_calendar_events_week ON calendar_events(week_of);
CREATE INDEX idx_calendar_events_source ON calendar_events(source);

-- Weekly briefing documents generated by Claude.
-- One per week — contains AI-generated research briefing for all events that week.
CREATE TABLE calendar_briefings (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  week_of TEXT NOT NULL UNIQUE,        -- YYYY-MM-DD (Monday of the week)
  title TEXT NOT NULL,                 -- e.g., "Week of March 30, 2026"
  content TEXT NOT NULL,               -- Full markdown briefing
  event_count INTEGER NOT NULL,        -- How many events were included
  model TEXT,                          -- Which Claude model generated this
  generated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
