-- Caches Sonnet-generated narrative prose for diagnostic surfaces. One row
-- per (scope, surface_key, week_of). Generated by the Sunday briefing
-- pipeline; on-demand fallback for first visit in a new week.
--
-- surface_key examples:
--   'factor-analysis'   — Quant Factor Analysis card
--   'risk-metrics'      — Risk Metrics card
--   'position-risk'     — Position Risk card
--   'factor-heatmap'    — Factor Heatmap card
--
-- week_of is the Monday of the ISO week as YYYY-MM-DD.

CREATE TABLE IF NOT EXISTS analysis_narratives (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  scope TEXT NOT NULL,
  surface_key TEXT NOT NULL,
  week_of TEXT NOT NULL,
  narrative_md TEXT NOT NULL,
  generated_at TEXT NOT NULL,
  model_used TEXT NOT NULL,
  UNIQUE (scope, surface_key, week_of)
);

CREATE INDEX IF NOT EXISTS idx_analysis_narratives_scope_week
  ON analysis_narratives(scope, week_of);
