-- Caches Sonnet-generated macro themes for a given (scope, week). One row per
-- (scope, week_of). Generated by the Sunday briefing pipeline; on-demand
-- regen rate-limited 1/day/scope.

CREATE TABLE IF NOT EXISTS analysis_macro_themes (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  week_of TEXT NOT NULL,
  scope TEXT NOT NULL,
  themes_json TEXT NOT NULL,
  source_summary TEXT,
  generated_at TEXT NOT NULL,
  model_used TEXT NOT NULL,
  UNIQUE (week_of, scope)
);

CREATE INDEX IF NOT EXISTS idx_analysis_macro_themes_week_scope
  ON analysis_macro_themes(week_of, scope);
