/**
 * Convert briefing markdown to styled HTML suitable for email clients.
 * Uses inline styles only (no CSS classes) for maximum email client compatibility.
 *
 * Handles the subset of markdown Claude produces in briefings:
 * ##/### headers, **bold**, *italic*, - bullet lists, paragraphs, ---
 */

const COLORS = {
  bg: "#080B12",
  panel: "#0F1219",
  border: "#1E2534",
  text: "#E2E6F0",
  dimText: "#8B95A8",
  gold: "#C9A44E",
  heading: "#F0F2F7",
};

export function briefingToHtml(markdown: string, title: string): string {
  const bodyHtml = convertMarkdown(markdown);

  return `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body style="margin:0; padding:0; background-color:${COLORS.bg}; font-family:system-ui,-apple-system,sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background-color:${COLORS.bg};">
    <tr><td align="center" style="padding:24px 16px;">
      <table width="600" cellpadding="0" cellspacing="0" style="max-width:600px; width:100%;">
        <!-- Header -->
        <tr><td style="padding:20px 24px; background-color:${COLORS.panel}; border:1px solid ${COLORS.border}; border-radius:12px 12px 0 0;">
          <h1 style="margin:0; font-size:20px; color:${COLORS.gold}; font-weight:600;">Vanguard Dashboard</h1>
          <p style="margin:6px 0 0; font-size:13px; color:${COLORS.dimText};">${title}</p>
        </td></tr>
        <!-- Body -->
        <tr><td style="padding:24px; background-color:${COLORS.panel}; border-left:1px solid ${COLORS.border}; border-right:1px solid ${COLORS.border}; border-bottom:1px solid ${COLORS.border}; border-radius:0 0 12px 12px; color:${COLORS.text}; font-size:14px; line-height:1.65;">
          ${bodyHtml}
        </td></tr>
        <!-- Footer -->
        <tr><td style="padding:16px 24px; text-align:center;">
          <p style="margin:0; font-size:11px; color:${COLORS.dimText};">
            Generated by Vanguard Dashboard &middot; Automated weekly briefing
          </p>
        </td></tr>
      </table>
    </td></tr>
  </table>
</body>
</html>`;
}

function convertMarkdown(md: string): string {
  const lines = md.split("\n");
  const output: string[] = [];
  let inList = false;

  for (let i = 0; i < lines.length; i++) {
    let line = lines[i];

    // Horizontal rule
    if (/^---+$/.test(line.trim())) {
      if (inList) { output.push("</ul>"); inList = false; }
      output.push(`<hr style="border:none; border-top:1px solid ${COLORS.border}; margin:16px 0;">`);
      continue;
    }

    // Headers
    if (line.startsWith("### ")) {
      if (inList) { output.push("</ul>"); inList = false; }
      const text = inlineFormat(line.slice(4));
      output.push(`<h3 style="margin:20px 0 8px; font-size:15px; color:${COLORS.heading}; font-weight:600;">${text}</h3>`);
      continue;
    }
    if (line.startsWith("## ")) {
      if (inList) { output.push("</ul>"); inList = false; }
      const text = inlineFormat(line.slice(3));
      output.push(`<h2 style="margin:24px 0 10px; font-size:17px; color:${COLORS.gold}; font-weight:600; border-bottom:1px solid ${COLORS.border}; padding-bottom:6px;">${text}</h2>`);
      continue;
    }
    if (line.startsWith("# ")) {
      if (inList) { output.push("</ul>"); inList = false; }
      const text = inlineFormat(line.slice(2));
      output.push(`<h1 style="margin:0 0 16px; font-size:20px; color:${COLORS.heading}; font-weight:700;">${text}</h1>`);
      continue;
    }

    // Blockquote
    if (line.startsWith("> ")) {
      if (inList) { output.push("</ul>"); inList = false; }
      const text = inlineFormat(line.slice(2));
      output.push(`<p style="margin:8px 0; padding:8px 12px; border-left:3px solid ${COLORS.gold}; color:${COLORS.dimText}; font-size:13px; line-height:1.5;">${text}</p>`);
      continue;
    }

    // Bullet list items (-, *, or numbered)
    const bulletMatch = line.match(/^(\s*)[-*]\s+(.+)/);
    const numberedMatch = line.match(/^(\s*)\d+\.\s+(.+)/);
    if (bulletMatch || numberedMatch) {
      const match = bulletMatch ?? numberedMatch!;
      const indent = match[1].length;
      const text = inlineFormat(match[2]);
      if (!inList) { output.push(`<ul style="margin:8px 0; padding-left:20px;">`); inList = true; }
      const marginLeft = indent > 2 ? "margin-left:16px;" : "";
      output.push(`<li style="margin:4px 0; color:${COLORS.text}; ${marginLeft}">${text}</li>`);
      continue;
    }

    // Close list if non-list line
    if (inList && line.trim() === "") {
      output.push("</ul>");
      inList = false;
      continue;
    }
    if (inList && line.trim() !== "") {
      output.push("</ul>");
      inList = false;
    }

    // Empty line = paragraph break
    if (line.trim() === "") {
      continue;
    }

    // Regular paragraph
    output.push(`<p style="margin:8px 0; color:${COLORS.text};">${inlineFormat(line)}</p>`);
  }

  if (inList) output.push("</ul>");

  return output.join("\n");
}

/** Convert inline markdown (bold, italic, links) to HTML. */
function inlineFormat(text: string): string {
  // Links: [text](url) — must run before bold/italic to avoid [**text**](url) issues
  text = text.replace(
    /\[([^\]]+)\]\(([^)]+)\)/g,
    `<a href="$2" style="color:${COLORS.gold}; text-decoration:underline;">$1</a>`
  );
  // Bold: **text** or __text__
  text = text.replace(/\*\*(.+?)\*\*/g, `<strong style="color:${COLORS.heading};">$1</strong>`);
  text = text.replace(/__(.+?)__/g, `<strong style="color:${COLORS.heading};">$1</strong>`);
  // Italic: *text* or _text_
  text = text.replace(/\*(.+?)\*/g, "<em>$1</em>");
  text = text.replace(/_(.+?)_/g, "<em>$1</em>");
  // Inline code
  text = text.replace(/`(.+?)`/g, `<code style="background:${COLORS.bg}; padding:1px 4px; border-radius:3px; font-size:13px;">$1</code>`);
  return text;
}
